# Generated by Django 4.0 on 2023-09-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_rename_data_cadastro_user_userdata_cadastro_and_more (9)'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserNumero', models.IntegerField()),
                ('UserRevisao', models.IntegerField()),
                ('UserOperador', models.CharField(max_length=40)),
                ('UserProduto', models.CharField(max_length=20)),
                ('UserMaquina', models.IntegerField()),
                ('UserMetros', models.IntegerField()),
                ('UserPeso', models.FloatField()),
                ('UserCliente', models.IntegerField()),
                ('UserNumDefeitos', models.IntegerField()),
                ('UserRefugo', models.FloatField()),
                ('UserLotes', models.CharField(max_length=40)),
                ('UserData_cadastro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
