# Generated by Django 4.0 on 2023-09-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_alter_revisao_usercliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisao',
            name='UserLotes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revisao',
            name='UserUrdideira',
            field=models.CharField(max_length=100),
        ),
    ]
